name: Vercel Production Deploy

on:
  push:
    branches:
      - "**" # Trigger on every branch push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.16.0" # or your Node.js version

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel Production
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          vercel --prod --confirm
